maintainer       "Librato"
maintainer_email "metrics@librato.com"
license          "All rights reserved"
description      "Installs/Configures basenode"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.1"

recipe "basenode", "Basenode recipes"
recipe "basenode::setup_firstboot", "Setup firstboot script"
recipe "basenode::firstboot", "Firstboot scripts"
recipe "basenode::add_users", "Add users on boot"
recipe "basenode::iptables", "Set iptables on boot"
recipe "basenode::statsite", "Setup statsite config files"
recipe "basenode::jstatd", "Setup jstatd service"
recipe "basenode::collectd_librato", "Enable collectd to librato"
